/** Emoji arama: "emoji kalp", ":gül", ":fire". Türkçe ve İngilizce anahtar kelimeler. */
const EMOJI: [string, string][] = [
  ["😀", "gülümseme mutlu smile happy"],
  ["😂", "gülmek kahkaha ağlayarak lol laugh"],
  ["🤣", "yerlere yatmak gülme rofl"],
  ["😊", "utangaç mutlu blush"],
  ["😍", "aşık kalp göz love"],
  ["😘", "öpücük kiss"],
  ["😎", "havalı gözlük cool"],
  ["🤔", "düşünmek hmm think"],
  ["😴", "uyku uyumak sleep"],
  ["😢", "üzgün ağlamak sad cry"],
  ["😭", "hüngür ağlamak sob"],
  ["😡", "kızgın sinirli angry"],
  ["🤯", "şok beyin patladı mind blown"],
  ["🥳", "parti kutlama party"],
  ["😅", "ter gergin sweat"],
  ["🙃", "ters yüz upside"],
  ["😬", "yüz buruşturma grimace"],
  ["🥺", "yalvarmak pleading"],
  ["😇", "melek angel"],
  ["🤡", "palyaço clown"],
  ["💀", "ölü kafatası skull dead"],
  ["👻", "hayalet ghost"],
  ["👍", "beğen tamam onay like ok thumbs"],
  ["👎", "beğenme dislike"],
  ["👏", "alkış clap"],
  ["🙏", "lütfen dua teşekkür pray thanks"],
  ["💪", "güç kas strong"],
  ["👋", "selam el sallama wave hi"],
  ["🤝", "anlaşma tokalaşma handshake"],
  ["✌️", "barış zafer peace"],
  ["👀", "göz bakmak eyes"],
  ["❤️", "kalp aşk sevgi heart love red"],
  ["💔", "kırık kalp broken heart"],
  ["💙", "mavi kalp blue heart"],
  ["💚", "yeşil kalp green heart"],
  ["🖤", "siyah kalp black heart"],
  ["✨", "parıltı sparkle"],
  ["🔥", "ateş alev fire lit"],
  ["⭐", "yıldız star"],
  ["🌙", "ay gece moon"],
  ["☀️", "güneş sun"],
  ["🌧️", "yağmur rain"],
  ["❄️", "kar snow"],
  ["⚡", "şimşek elektrik zap"],
  ["🌈", "gökkuşağı rainbow"],
  ["🌹", "gül çiçek rose flower"],
  ["🌸", "kiraz çiçeği blossom"],
  ["🍀", "yonca şans luck"],
  ["🎉", "konfeti kutlama tada party"],
  ["🎂", "pasta doğum günü cake birthday"],
  ["🎁", "hediye gift"],
  ["🎮", "oyun gamepad game"],
  ["🎧", "kulaklık müzik headphones"],
  ["🎵", "müzik nota music"],
  ["⚽", "futbol top football soccer"],
  ["🏀", "basketbol basketball"],
  ["🏆", "kupa şampiyon trophy"],
  ["🚀", "roket rocket"],
  ["✈️", "uçak plane"],
  ["🚗", "araba car"],
  ["🏠", "ev home house"],
  ["💻", "bilgisayar laptop computer"],
  ["📱", "telefon phone"],
  ["💡", "fikir ampul idea"],
  ["📌", "raptiye pin"],
  ["✅", "tamam onay check done"],
  ["❌", "hayır çarpı no cross"],
  ["⚠️", "uyarı dikkat warning"],
  ["💯", "yüz tam puan hundred"],
  ["💰", "para money"],
  ["☕", "kahve coffee"],
  ["🍕", "pizza"],
  ["🍔", "hamburger burger"],
  ["🍺", "bira beer"],
  ["🐱", "kedi cat"],
  ["🐶", "köpek dog"],
  ["🦊", "tilki fox"],
  ["🐸", "kurbağa frog"],
  ["🇹🇷", "türkiye bayrak turkey flag"],
];

export function searchEmoji(q: string): string[] {
  const m = /^(?:emoji\s+|:)(.+)$/i.exec(q.trim());
  if (!m) return [];
  const term = m[1].toLocaleLowerCase("tr").trim();
  if (!term) return [];
  return EMOJI.filter(([, words]) => words.split(" ").some((w) => w.startsWith(term)))
    .map(([e]) => e)
    .slice(0, 8);
}
